# Generated by Django 4.0.4 on 2023-07-28 10:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('list', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='HomePage',
        ),
    ]
