# Generated by Django 4.0.4 on 2023-07-31 07:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('list', '0003_images'),
    ]

    operations = [
        migrations.AddField(
            model_name='images',
            name='name',
            field=models.CharField(default='img', max_length=300),
        ),
    ]
