# Generated by Django 4.0.4 on 2023-08-12 23:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('list', '0008_rename_goal_timebox_remove_schedule_user_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='timebox',
            name='weekNum',
            field=models.CharField(default=0, max_length=200),
        ),
    ]
