# Generated by Django 4.0.4 on 2023-08-17 03:12

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('list', '0011_weekly_goal_quarter_goal_monthly_goal'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='quarter_goal',
            new_name='Quarterly_goal',
        ),
    ]
